name: Compilar APK Android

on:
  push:
    branches: [ main ]  # Executa toda vez que você der "git push" na branch main
  workflow_dispatch:     # Permite que você clique num botão para rodar manualmente

jobs:
  build:
    runs-on: ubuntu-22-04

    steps:
    - name: Baixar o código do repositório
      uses: actions/checkout@v6

    - name: Configurar o Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10.12'

    - name: Instalar dependências do sistema Linux
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libltdl-dev libffi-dev libssl-dev autoconf automake libtool curl unzip zip
        pip install --upgrade pip
        pip install buildozer cython virtualenv

    - name: Compilar o APK com o Buildozer
      run: |
        buildozer appclean
        # O "yes |" aceita automaticamente as licenças do Android SDK que aparecerem
        yes | buildozer -v android debug

    - name: Salvar o APK gerado
      uses: actions/upload-artifact@v6
      with:
        name: Jogo-Android-APK
        path: bin/*.apk
